apiVersion: v1
kind: Secret
metadata:
  name: ms-delivery-secret
type: Opaque
data:
  APP_KEY: TzJnNlpIVWY4TXZBRW5hdFVsSW5DY3NBam80T0phSTA=
  RABBITMQ_USER: Z3Vlc3Q=
  RABBITMQ_PASSWORD: Z3Vlc3Q=
  GEOAPIFY_TOKEN: NzU3YmRiYmMzMGI0NDVkOTlmN2JlYjlhZjdmMjJhMTI=
